# Generated by Django 2.1.1 on 2018-09-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(default=1, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(default=1, help_text='Exemplo: (XX) XXXXX-XXXX', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(help_text='Através deste endereço eletrônico você receberá sua confirmação de inscrição', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inscricao.Curso', verbose_name='Curso de graduação'),
            preserve_default=False,
        ),
    ]
