# Generated by Django 2.1.1 on 2018-09-18 19:37

from django.db import migrations, models
import django.db.models.deletion
import inscricao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_auto_20180918_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[inscricao.validators.validate_CPF], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Selecione um curso da lista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscricao.Curso', verbose_name='Curso de graduação'),
        ),
    ]
